/*
 ADOBE CONFIDENTIAL
 ___________________

 Copyright 2011 Adobe Systems Incorporated
 All Rights Reserved.

 NOTICE:  All information contained herein is, and remains
 the property of Adobe Systems Incorporated and its suppliers,
 if any.  The intellectual and technical concepts contained
 herein are proprietary to Adobe Systems Incorporated and its
 suppliers and may be covered by U.S. and Foreign Patents,
 patents in process, and are protected by trade secret or copyright law.
 Dissemination of this information or reproduction of this material
 is strictly forbidden unless prior written permission is obtained
 from Adobe Systems Incorporated.
*/
if(typeof Muse=="undefined")window.Muse={};Muse.Assert={};Muse.Assert.fail=function(a){alert("MuseJSAssert: "+a)};$.extend($.browser,{SafariMobile:navigator.userAgent.toLowerCase().match(/iP(hone|ad)/i)});if(!Array.indexOf)Array.prototype.indexOf=function(a){for(var b=0;b<this.length;++b)if(this[b]==a)return b;return-1};Muse.Plugins={};Muse.Utils={};Muse.Utils.addLoadListener=function(a){$(document).ready(a)};
Muse.Utils.runLoadListeners=function(){if(Muse.Utils.loadListeners)for(var a=0;a<Muse.Utils.loadListeners.length;a++)try{Muse.Utils.loadListeners[a]()}catch(b){Muse.Assert.fail("LoadListener failed: "+b)}};Muse.Utils.selectorFns=[];Muse.Utils.addSelectorFn=function(a,b){Muse.Utils.selectorFns.push({selector:a,selFn:b})};
Muse.Utils.addLoadListener(function(){for(var a=0;a<Muse.Utils.selectorFns.length;a++)try{Spry.$$(Muse.Utils.selectorFns[a].selector).forEach(Muse.Utils.selectorFns[a].selFn)}catch(b){Muse.Assert.fail("Error calling selector function:"+b)}});Muse.Utils.isTouchDevice=function(){if(typeof Muse.Utils.isTouchDevice.flag=="undefined")try{document.createEvent("TouchEvent"),Muse.Utils.isTouchDevice.flag=!0}catch(a){Muse.Utils.isTouchDevice.flag=!1}return Muse.Utils.isTouchDevice.flag};
Muse.Utils.wrapElement=function(a,b){a.parentNode.replaceChild(b,a);b.appendChild(a)};Muse.Utils.firstChild=function(a,b){for(var c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];if(d.nodeType==1&&(!b||b.matches(d)))return d}return null};Muse.Utils.firstDescendant=function(a,b,c){for(var d=0;d<a.childNodes.length;d++){var e=a.childNodes[d];if(e.nodeType==1){if(!b||b.matches(e))return e;if(!c||!c.matches(e))if(e=Muse.Utils.firstDescendant(e,b,c))return e}}return null};
Muse.Utils.descendants=function(a,b,c,d){if(!d)d=[],d.forEach=function(a){for(var b=0;b<this.length;b++)if(a(this[b]))break},d.forEachTry=function(a){for(var b=0;b<this.length;b++)try{if(a(this[b]))break}catch(c){}};for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes[e];f.nodeType==1&&((!b||b.matches(f))&&d.push(f),(!c||!c.matches(f))&&Muse.Utils.descendants(f,b,c,d))}return d};Muse.Utils.children=function(a,b){return Muse.Utils.descendants(a,b,Muse.Utils.Match.always)};Muse.Utils.Match={};
Muse.Utils.Match.ByClass=function(a){this.cl=a};Muse.Utils.Match.ByClass.prototype.matches=function(a){return Spry.Utils.hasClassName(a,this.cl)};Muse.Utils.Match.ByNodeName=function(a){this.nm=a.toLowerCase()};Muse.Utils.Match.ByNodeName.prototype.matches=function(a){return this.nm==a.nodeName.toLowerCase()};Muse.Utils.Match.ByFixed=function(a){this.matchResult=a};Muse.Utils.Match.ByFixed.prototype.matches=function(){return this.matchResult};Muse.Utils.Match.byClass=function(a){return new Muse.Utils.Match.ByClass(a)};
Muse.Utils.Match.byNodeName=function(a){return new Muse.Utils.Match.ByNodeName(a)};Muse.Utils.Match.byFixed=function(a){return new Muse.Utils.Match.ByFixed(a)};Muse.Utils.Match.always=Muse.Utils.Match.byFixed(!0);Muse.Utils.Match.never=Muse.Utils.Match.byFixed(!1);Muse.Utils.moveChildren=function(a,b){for(;a.childNodes.length>0;)b.appendChild(a.childNodes[0])};Muse.Utils.copyChildren=function(a,b){for(var c=0;c<a.childNodes.length;c++)b.appendChild(a.childNodes[c].cloneNode(!0))};
Muse.Utils.copyChildrenBefore=function(a,b){for(var c=0;c<a.childNodes.length;c++)b.parentNode.insertBefore(a.childNodes[c].cloneNode(!0),b)};Muse.Utils.pixelRound=function(a){return Math.floor((a*100+0.5)/100)};Muse.Utils.getCurrentHTMLFileName=function(a){var b=document.location.href,b=b.charAt(b.length-1)=="/"?"index":b.substring(b.lastIndexOf("/")+1,b.lastIndexOf("."));a&&(b+=".html");return b};
Muse.Utils.getPageStyleSheet=function(){for(var a="/"+Muse.Utils.getCurrentHTMLFileName(!1).toLowerCase()+".css",b=0;b<document.styleSheets.length;++b){var c=document.styleSheets[b];if(c.href&&c.href.toLowerCase().indexOf(a)!=-1)return c}};
Muse.Utils.getStyleSheetRuleById=function(a,b){var c=!1,d="#"+b.toLowerCase(),e=a.cssRules;if(!e)c=!0,e=a.rules;if(e)for(var f=0;f<e.length;++f){var g=e[f];if(c){if(g.selectorText.toLowerCase()==d)return g}else if(g.selectorText.toLowerCase().split(", ").indexOf(d)!=-1)return g}return null};Muse.Utils.setRuleProperty=function(a,b,c){a.style.setProperty?a.style.setProperty(b,c,""):a.style.setAttribute(b,c,0)};
Muse.Utils.removeRuleProperty=function(a,b){a.style.removeProperty?a.style.removeProperty(b):a.style.removeAttribute(b,0)};
Muse.Utils.cloneStyleSheetRule=function(a){if(typeof Muse.Utils.cloneStyleSheetRule.newNumber=="undefined")Muse.Utils.cloneStyleSheetRule.newNumber=1;var b=Muse.Utils.getPageStyleSheet(a),c=Muse.Utils.getStyleSheetRuleById(b,a),d="c"+Muse.Utils.cloneStyleSheetRule.newNumber++,e="#"+d;b.insertRule?b.insertRule(c.cssText.replace("#"+a,e),b.cssRules.length):b.addRule(e,c.style.cssText);return d};
Muse.Utils.toCamelCase=function(a){for(var b=Muse.Utils.toCamelCase.exp;b.test(a);a=a.replace(b,RegExp.$1.toUpperCase()));return a};Muse.Utils.toCamelCase.exp=/-([a-z])/;Muse.Utils.getStyleValue=function(a,b){var c=a.style[Muse.Utils.toCamelCase(b)];c||(document.defaultView?c=document.defaultView.getComputedStyle(a,"").getPropertyValue(b):a.currentStyle&&(c=a.currentStyle[Muse.Utils.toCamelCase(b)]));c&&c.match(/(\d+)px/)&&(c=parseInt(c.substring(0,c.length-2)));return c};var actionStack=[];
Muse.Utils.redirectHyperlink=function(a){actionStack=[];var b=a.href,c=$(a).attr("target");if(!c){var c=b.lastIndexOf("/"),d=b.lastIndexOf("#");if(d>c){var e=Muse.Utils.getCurrentHTMLFileName(!0);if(b.substring(c+1,d)==e){var f=b.substring(d);if(a=$(a).attr("class").match(/anim_(\w+)/))if(a=a[1],b=$(f).offset().top,c=$(f).offset().left,Muse.Utils.isTouchDevice())$(window).scrollTop(b),$(window).scrollLeft(c);else{!jQuery.browser.msie||jQuery.browser.version>7?$("html,body").animate({scrollTop:b,scrollLeft:c},
1E3,a,function(){window.location.hash=f}):$("html,body").animate({scrollTop:b,scrollLeft:c},1E3,a);return}window.location.hash=f;return}}c="_self"}window.open(b,c)};Muse.Utils.redirectHyperlinkInBackground=function(a){actionStack=[];thisWindow=window.self;window.open(a);thisWindow.focus()};Muse.Utils.isMouseLeftClick=function(a){return a.which==1};Muse.Utils.isMouseMiddleClick=function(a){return a.which==2};Muse.Utils.isRedirectLinkKeyboardAction=function(a){return a.which==13};
Muse.Utils.addHyperlinkAnchor=function(a){a=$(a);a.bind("mousedown",function(a){(Muse.Utils.isMouseLeftClick(a)||Muse.Utils.isMouseMiddleClick(a))&&actionStack.push(this)});a.bind("mouseup keyup",function(a){if(Muse.Utils.isMouseLeftClick(a)&&actionStack.indexOf(this)!=-1)a.ctrlKey?Muse.Utils.redirectHyperlinkInBackground(this.href):Muse.Utils.redirectHyperlink(this);else if(Muse.Utils.isMouseMiddleClick(a)&&actionStack.indexOf(this)!=-1)if(jQuery.browser.webkit||!a.target.href&&jQuery.browser.msie)Muse.Utils.redirectHyperlinkInBackground(this.href);
else return actionStack=[],!0;else Muse.Utils.isRedirectLinkKeyboardAction(a)&&Muse.Utils.redirectHyperlink(this);return!1});a.bind("click",function(){return!1})};
Muse.Utils.addHyperlinkBlock=function(a){$(a.parentNode).bind("mousedown",function(a){(Muse.Utils.isMouseLeftClick(a)||Muse.Utils.isMouseMiddleClick(a))&&actionStack.push(this);return!1});$(a.parentNode).bind("mouseup keyup",function(b){Muse.Utils.isMouseLeftClick(b)&&actionStack.indexOf(this)!=-1?b.ctrlKey?Muse.Utils.redirectHyperlinkInBackground(a.href):Muse.Utils.redirectHyperlink(a):Muse.Utils.isMouseMiddleClick(b)&&actionStack.indexOf(this)!=-1?Muse.Utils.redirectHyperlinkInBackground(a.href):
Muse.Utils.isRedirectLinkKeyboardAction(b)&&Muse.Utils.redirectHyperlink(a);return!1});$(a.parentNode).bind("click",function(){return!1})};
Muse.Utils.getNaturalWidth=function(a){var b=-1;a.naturalWidth!=null?b=a.naturalWidth:a.runtimeStyle?(a.runtimeStyle.width="auto",a.runtimeStyle.height="auto",a.runtimeStyle.borderWidth="0",a.runtimeStyle.padding="0",b=a.offsetWidth,a.runtimeStyle.width="",a.runtimeStyle.height="",a.runtimeStyle.borderWidth="",a.runtimeStyle.padding=""):(a=a.cloneNode(!0),a.className="",a.style.width="auto !important",a.style.height="auto !important",a.style.borderWidth="0 !important",a.style.padding="0 !important",
b=a.width);return b};
Muse.Utils.getNaturalHeight=function(a){var b=-1;a.naturalHeight!=null?b=a.naturalHeight:a.runtimeStyle?(a.runtimeStyle.width="auto",a.runtimeStyle.height="auto",a.runtimeStyle.borderWidth="0",a.runtimeStyle.padding="0",b=a.offsetHeight,a.runtimeStyle.width="",a.runtimeStyle.height="",a.runtimeStyle.borderWidth="",a.runtimeStyle.padding=""):(a=a.cloneNode(!0),a.className="",a.style.width="auto !important",a.style.height="auto !important",a.style.borderWidth="0 !important",a.style.padding="0 !important",
b=a.height);return b};Muse.Utils.needPIE=function(){if(!Muse.Utils.havePIE)$.ajax({url:"scripts/1.1/pie.js",dataType:"script",async:!1}),Muse.Utils.havePIE=!0};Muse.Utils.transformMarkupToFixBrowserProblemsPreInit=function(){jQuery.browser.msie?(jQuery("html").addClass("ie"),jQuery.browser.version<8&&Muse.Utils.changeLItoDIVs()):jQuery.browser.SafariMobile&&jQuery("body").css("-webkit-text-size-adjust","none")};
Muse.Utils.transformMarkupToFixBrowserProblems=function(){Muse.Utils.havePIE=!1;jQuery.browser.msie&&(jQuery.browser.version<9&&(Muse.Utils.applyIEFilterToPNGImages(),Muse.Utils.addRoundedCorners(),Muse.Utils.addRGBA()),jQuery.browser.version<8&&Muse.Utils.fixWidthsForClearingInIE7());(jQuery.browser.msie&&jQuery.browser.version<9||jQuery.browser.webkit)&&Muse.Utils.insertEmptyDivAfterPinnedColumnElements()};
Muse.Utils.applyIEFilterToPNGImages=function(){jQuery.browser.msie&&jQuery.browser.version<9&&$("body *").each(function(){var a=$(this);if(a.css("background-image").match(/\b.png/i)||this.nodeName&&this.nodeName.toLowerCase()=="img"&&a.attr("src").match(/\b.png/i)){var b=a.css("filter");a.css("filter",b?b+" progid:DXImageTransform.Microsoft.gradient(startColorstr=#00FFFFFF,endColorstr=#00FFFFFF)":"progid:DXImageTransform.Microsoft.gradient(startColorstr=#00FFFFFF,endColorstr=#00FFFFFF)")}})};
Muse.Utils.insertEmptyDivAfterPinnedColumnElements=function(){$(".pinned-colelem").each(function(){$("<div class='colelem'/>").insertAfter($(this))})};Muse.Utils.fixPNGImages=function(){$("body *").each(function(){var a=$(this);if(a.css("background-image").match(/\b.png/i)||this.nodeName&&this.nodeName.toLowerCase()=="img"&&a.attr("src").match(/\b.png/i))Muse.Utils.needPIE(),a.css("-pie-png-fix","true"),PIE.attach(this)})};
Muse.Utils.addRoundedCorners=function(){$(".rounded-corners").each(function(){Muse.Utils.needPIE();var a=$(this);if(jQuery.browser.msie&&jQuery.browser.version<8&&(a.css("border-left-width")==0||a.css("border-left-style")=="none")&&(a.css("border-right-width")==0||a.css("border-right-style")=="none")&&(a.css("border-top-width")==0||a.css("border-top-style")=="none")&&(a.css("border-bottom-width")==0||a.css("border-bottom-style")=="none"))a.css({"border-right-width":"1px","border-right-style":"solid",
"border-right-color":a.css("background-color")}),a.width(a.width()-1);PIE.attach(this)})};Muse.Utils.addRGBA=function(){$(".rgba-background").each(function(){Muse.Utils.needPIE();PIE.attach(this)})};Muse.Utils.fixWidthsForClearingInIE7=function(){$(".colelem").each(function(){var a=$(this).offset().left-$(this).parent().offset().left;if($(this).width()<1||$(this).width()+a<1)$(this).css("width",(a<0?1-a:1)+"px")})};
Muse.Utils.changeLItoDIVs=function(){var a=function(){var a=$(this),c=$("<div/>");c.addClass(a.attr("class"));c.attr("id",a.attr("id"));c.append(a.contents());a.replaceWith(c)};$("ul").each(function(){$(this).find("li").each(a)});$("ul").each(a)};Muse.Utils.showWidgetsWhenReady=function(){jQuery(".disn").removeClass("disn");jQuery(".invi").removeClass("invi");jQuery(".widget_invisible").removeClass("widget_invisible")};
Muse.Utils.refreshIframesAndObjectsToPauseMedia=function(a){a.filter(function(){return $(this).css("display")!="none"}).each(function(){$("iframe, object",this).each(function(){var a=$(this).next();a.length==0?(a=$(this).parent(),$(this).detach().appendTo(a)):$(this).detach().insertBefore(a)});$("video",this).each(function(){$(this).get(0).pause&&$(this).get(0).pause()})})};
